on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Build on Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        racket-version: ["stable"]
        racket-variant: ["BC", "CS"]
    steps:
      - uses: actions/checkout@master
      - uses: Bogdanp/setup-racket@v1.7
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}
      - name: Install dependencies
        run: |
          sudo wget -o nghttp2-proxy.deb \
            https://launchpad.net/ubuntu/+archive/primary/+files/nghttp2-proxy_1.43.0-1_amd64.deb && \
            sudo dpkg -i nghttp2-proxy.deb
      - name: Install the package
        run: raco pkg install --auto http123-lib/ http123/
      - name: Run the tests
        run: raco test -c http123
